-- =====================================================
-- Migration 070: Create Lottery System
-- =====================================================
-- Descrizione: Sistema completo per gestire lotterie
-- Eventi, biglietti, estrazioni, vincitori
-- =====================================================

-- =====================================================
-- LOTTERY EVENTS TABLE
-- =====================================================

CREATE TABLE IF NOT EXISTS public.lottery_events (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id UUID NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,

  -- Event Info
  name VARCHAR(255) NOT NULL,
  description TEXT,
  event_date TIMESTAMPTZ NOT NULL,
  extraction_date TIMESTAMPTZ NOT NULL,

  -- Pricing
  ticket_price DECIMAL(10, 2) NOT NULL DEFAULT 5.00,

  -- Prize Info
  prize_name VARCHAR(255),
  prize_value DECIMAL(10, 2),
  prize_description TEXT,

  -- Branding Colors (JSON per personalizzazione)
  brand_colors JSONB DEFAULT '{"primary": "#e74c3c", "secondary": "#c0392b", "accent": "#f39c12"}',

  -- Status
  status VARCHAR(50) NOT NULL DEFAULT 'active',
  -- Possible values: 'draft', 'active', 'closed', 'extracted'

  -- Stats
  total_tickets_sold INTEGER DEFAULT 0,
  total_revenue DECIMAL(10, 2) DEFAULT 0.00,

  -- Timestamps
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  extracted_at TIMESTAMPTZ,

  -- Constraints
  CONSTRAINT valid_dates CHECK (extraction_date >= event_date),
  CONSTRAINT valid_price CHECK (ticket_price >= 0),
  CONSTRAINT valid_status CHECK (status IN ('draft', 'active', 'closed', 'extracted'))
);

-- Indexes
CREATE INDEX idx_lottery_events_org ON public.lottery_events(organization_id);
CREATE INDEX idx_lottery_events_status ON public.lottery_events(status);
CREATE INDEX idx_lottery_events_extraction_date ON public.lottery_events(extraction_date);

-- =====================================================
-- LOTTERY TICKETS TABLE
-- =====================================================

CREATE TABLE IF NOT EXISTS public.lottery_tickets (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  event_id UUID NOT NULL REFERENCES public.lottery_events(id) ON DELETE CASCADE,
  organization_id UUID NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,

  -- Ticket Info
  ticket_number VARCHAR(20) NOT NULL,
  -- Format: "XXX-XXX" generated randomly

  -- Customer Info
  customer_id UUID REFERENCES public.customers(id) ON DELETE SET NULL,
  customer_name VARCHAR(255) NOT NULL,
  customer_email VARCHAR(255),
  customer_phone VARCHAR(50),

  -- Fortune Message (generated by AI)
  fortune_message TEXT,

  -- Purchase Info
  purchased_by_staff_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  purchased_by_staff_name VARCHAR(255),
  price_paid DECIMAL(10, 2) NOT NULL,

  -- Validation
  qr_code_data TEXT NOT NULL,
  -- QR code contains: event_id + ticket_id for validation

  is_validated BOOLEAN DEFAULT false,
  validated_at TIMESTAMPTZ,

  -- Winner Info
  is_winner BOOLEAN DEFAULT false,
  won_at TIMESTAMPTZ,
  prize_claimed BOOLEAN DEFAULT false,
  prize_claimed_at TIMESTAMPTZ,

  -- Timestamps
  created_at TIMESTAMPTZ DEFAULT NOW(),

  -- Constraints
  CONSTRAINT unique_ticket_number_per_event UNIQUE (event_id, ticket_number),
  CONSTRAINT valid_price_paid CHECK (price_paid >= 0)
);

-- Indexes
CREATE INDEX idx_lottery_tickets_event ON public.lottery_tickets(event_id);
CREATE INDEX idx_lottery_tickets_org ON public.lottery_tickets(organization_id);
CREATE INDEX idx_lottery_tickets_customer ON public.lottery_tickets(customer_id);
CREATE INDEX idx_lottery_tickets_number ON public.lottery_tickets(ticket_number);
CREATE INDEX idx_lottery_tickets_qr ON public.lottery_tickets(qr_code_data);
CREATE INDEX idx_lottery_tickets_winner ON public.lottery_tickets(is_winner) WHERE is_winner = true;

-- =====================================================
-- LOTTERY EXTRACTIONS TABLE (History)
-- =====================================================

CREATE TABLE IF NOT EXISTS public.lottery_extractions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  event_id UUID NOT NULL REFERENCES public.lottery_events(id) ON DELETE CASCADE,
  organization_id UUID NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,

  -- Winner Info
  winning_ticket_id UUID NOT NULL REFERENCES public.lottery_tickets(id) ON DELETE CASCADE,
  winning_ticket_number VARCHAR(20) NOT NULL,
  winner_customer_name VARCHAR(255) NOT NULL,

  -- Extraction Info
  extracted_by_staff_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  extracted_by_staff_name VARCHAR(255),
  extraction_method VARCHAR(50) DEFAULT 'automatic',
  -- Possible values: 'automatic', 'manual'

  -- Stats at time of extraction
  total_participants INTEGER NOT NULL,

  -- Timestamps
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Indexes
CREATE INDEX idx_lottery_extractions_event ON public.lottery_extractions(event_id);
CREATE INDEX idx_lottery_extractions_org ON public.lottery_extractions(organization_id);
CREATE INDEX idx_lottery_extractions_ticket ON public.lottery_extractions(winning_ticket_id);

-- =====================================================
-- RLS POLICIES
-- =====================================================

-- Enable RLS
ALTER TABLE public.lottery_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.lottery_tickets ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.lottery_extractions ENABLE ROW LEVEL SECURITY;

-- LOTTERY EVENTS POLICIES

CREATE POLICY "Users can view events from their organizations"
  ON public.lottery_events FOR SELECT
  USING (
    organization_id IN (
      SELECT org_id FROM public.organization_users WHERE user_id = auth.uid()
    )
  );

CREATE POLICY "Org admins can create events"
  ON public.lottery_events FOR INSERT
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM public.organization_users
      WHERE user_id = auth.uid()
      AND org_id = organization_id
      AND role IN ('org_admin', 'super_admin')
    )
  );

CREATE POLICY "Org admins can update events"
  ON public.lottery_events FOR UPDATE
  USING (
    EXISTS (
      SELECT 1 FROM public.organization_users
      WHERE user_id = auth.uid()
      AND org_id = organization_id
      AND role IN ('org_admin', 'super_admin')
    )
  );

-- LOTTERY TICKETS POLICIES

CREATE POLICY "Users can view tickets from their organizations"
  ON public.lottery_tickets FOR SELECT
  USING (
    organization_id IN (
      SELECT org_id FROM public.organization_users WHERE user_id = auth.uid()
    )
  );

CREATE POLICY "Staff can create tickets"
  ON public.lottery_tickets FOR INSERT
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM public.organization_users
      WHERE user_id = auth.uid()
      AND org_id = organization_id
    )
  );

CREATE POLICY "Org admins can update tickets"
  ON public.lottery_tickets FOR UPDATE
  USING (
    EXISTS (
      SELECT 1 FROM public.organization_users
      WHERE user_id = auth.uid()
      AND org_id = organization_id
      AND role IN ('org_admin', 'super_admin')
    )
  );

-- LOTTERY EXTRACTIONS POLICIES

CREATE POLICY "Users can view extractions from their organizations"
  ON public.lottery_extractions FOR SELECT
  USING (
    organization_id IN (
      SELECT org_id FROM public.organization_users WHERE user_id = auth.uid()
    )
  );

CREATE POLICY "Org admins can create extractions"
  ON public.lottery_extractions FOR INSERT
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM public.organization_users
      WHERE user_id = auth.uid()
      AND org_id = organization_id
      AND role IN ('org_admin', 'super_admin')
    )
  );

-- =====================================================
-- FUNCTIONS
-- =====================================================

-- Function to generate unique ticket number
CREATE OR REPLACE FUNCTION public.generate_lottery_ticket_number(p_event_id UUID)
RETURNS VARCHAR AS $$
DECLARE
  v_ticket_number VARCHAR(20);
  v_exists BOOLEAN;
BEGIN
  LOOP
    -- Generate format: XXX-XXX (000-999 range)
    v_ticket_number := LPAD(FLOOR(RANDOM() * 1000)::TEXT, 3, '0') || '-' ||
                       LPAD(FLOOR(RANDOM() * 1000)::TEXT, 3, '0');

    -- Check if exists
    SELECT EXISTS(
      SELECT 1 FROM public.lottery_tickets
      WHERE event_id = p_event_id AND ticket_number = v_ticket_number
    ) INTO v_exists;

    EXIT WHEN NOT v_exists;
  END LOOP;

  RETURN v_ticket_number;
END;
$$ LANGUAGE plpgsql;

-- Function to update event stats
CREATE OR REPLACE FUNCTION public.update_lottery_event_stats()
RETURNS TRIGGER AS $$
BEGIN
  -- Update total tickets sold and revenue
  UPDATE public.lottery_events
  SET
    total_tickets_sold = (
      SELECT COUNT(*) FROM public.lottery_tickets WHERE event_id = NEW.event_id
    ),
    total_revenue = (
      SELECT COALESCE(SUM(price_paid), 0) FROM public.lottery_tickets WHERE event_id = NEW.event_id
    ),
    updated_at = NOW()
  WHERE id = NEW.event_id;

  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to update stats
CREATE TRIGGER update_event_stats_on_ticket_insert
  AFTER INSERT ON public.lottery_tickets
  FOR EACH ROW
  EXECUTE FUNCTION public.update_lottery_event_stats();

-- =====================================================
-- COMMENTS
-- =====================================================

COMMENT ON TABLE public.lottery_events IS 'Eventi lotteria per ogni organizzazione';
COMMENT ON TABLE public.lottery_tickets IS 'Biglietti venduti per le lotterie';
COMMENT ON TABLE public.lottery_extractions IS 'Storico estrazioni e vincitori';
COMMENT ON FUNCTION public.generate_lottery_ticket_number IS 'Genera numero biglietto univoco formato XXX-XXX';
